services:
  web:
    build: .
    command: python uptime_monitor/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A uptime_monitor worker --loglevel=info
    volumes:
      - .:/code
    working_dir: /code/uptime_monitor
    depends_on:
      - db
      - redis
    env_file:
      - .env