# Generated by Django 5.2 on 2025-04-25 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('check_interval', models.IntegerField(default=5, help_text='Check interval in minutes')),
                ('status', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, help_text='Optional webhook for alerts', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
