# Generated by Django 5.2 on 2025-04-23 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[
                 ('UP', 'UP'), ('DOWN', 'DOWN'), ('UNKNOWN', 'UNKNOWN')], max_length=10)),
                ('checked_at', models.DateTimeField()),
                ('monitored_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='history', to='monitor.monitoredurl')),
            ],
        ),
    ]
